name: Build & Deploy Java App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build jar
      run: ./mvnw clean package -DskipTests

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "target/*.jar"
        target: "/home/ec2-user"

    - name: SSH to EC2 and run app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop java-app || true
          docker rm java-app || true
          docker rmi java-spring-app || true
          docker build -t java-spring-app /home/ec2-user
          docker run -d -p 8080:8080 --name java-app java-spring-app
